server:
  port: 8081
spring:
  kafka:             
    producer:  
      properties:
         sasl.mechanism: PLAIN
         security.protocol: SASL_SSL         
         ssl:
            protocol: SSL          
            trust-store-location: classpath:/ssl/kafka.client.truststore.jks
            trust-store-password: tester
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
